[package]
name = "uint_execute"
version = "0.1.0"
authors = ["msyksphinz <msyksphinz.dev@gmail.com>"]
edition = "2018"

[dependencies]
mmap = "*"
libc = "*"
num = "*"
memmap = "*"
softfloat-wrapper-riscv = {path = "../softfloat-wrapper"}
softfloat-sys-riscv = {path = "../softfloat-sys"}
clap = "3.0.0-beta.1"
